## Scikit Learn

In [1]:
#Load the IRIS dataset from the Scikit learn library

from sklearn.datasets import load_iris
iris=load_iris()


In [14]:
#Store the feature matrix i.e. X and Response vector Y

X=iris.data
y=iris.target

In [24]:
# Store the feature names and target data

feature_names=iris.feature_names #['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target_data=iris.target_names   #['setosa', 'versicolor', 'virginica']

In [30]:
# Print the feature Names and target names of our data

print("feature Names ", feature_names,'\n')
print("Target Data   " , target_data)

feature Names  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 

Target Data    ['setosa' 'versicolor' 'virginica']


In [31]:
# check the type of X and y

print("Type of X is ", type(X)," and Type of y is :", type(y))

Type of X is  <class 'numpy.ndarray'>  and Type of y is : <class 'numpy.ndarray'>


In [36]:
# print the first 5 rows of an array

print("The top 5 rows of data :","\n", X[0:5])

The top 5 rows of data : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [37]:
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1) 

In [44]:
print('X Train Size',X_train.size)

print('X Test Size',X_test.size)

X Train Size 360
X Test Size 240


In [48]:
# printing the shapes of the new X objects 
print(X_train.shape) 
print(X_test.shape)  

(90, 4)
(60, 4)


In [49]:
# printing the shapes of the new y objects abs
print(y_train.shape) 
print(y_test.shape)

(90,)
(60,)


In [50]:
# training the model on training set 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [70]:
import pandas as pd

test_df=pd.DataFrame(X_test,)
test_df['labels']=y_test
print(test_df)



      0    1    2    3  labels
0   5.8  4.0  1.2  0.2       0
1   5.1  2.5  3.0  1.1       1
2   6.6  3.0  4.4  1.4       1
3   5.4  3.9  1.3  0.4       0
4   7.9  3.8  6.4  2.0       2
5   6.3  3.3  4.7  1.6       1
6   6.9  3.1  5.1  2.3       2
7   5.1  3.8  1.9  0.4       0
8   4.7  3.2  1.6  0.2       0
9   6.9  3.2  5.7  2.3       2
10  5.6  2.7  4.2  1.3       1
11  5.4  3.9  1.7  0.4       0
12  7.1  3.0  5.9  2.1       2
13  6.4  3.2  4.5  1.5       1
14  6.0  2.9  4.5  1.5       1
15  4.4  3.2  1.3  0.2       0
16  5.8  2.6  4.0  1.2       1
17  5.6  3.0  4.5  1.5       1
18  5.4  3.4  1.5  0.4       0
19  5.0  3.2  1.2  0.2       0
20  5.5  2.6  4.4  1.2       1
21  5.4  3.0  4.5  1.5       1
22  6.7  3.0  5.0  1.7       1
23  5.0  3.5  1.3  0.3       0
24  7.2  3.2  6.0  1.8       2
25  5.7  2.8  4.1  1.3       1
26  5.5  4.2  1.4  0.2       0
27  5.1  3.8  1.5  0.3       0
28  6.1  2.8  4.7  1.2       1
29  6.3  2.5  5.0  1.9       2
30  6.1  3.0  4.6  1.4       1
31  7.7 

In [71]:
# making predictions on the testing set 
y_pred = knn.predict(X_test) 

In [73]:
test_df['y_pred']=y_pred

In [74]:
test_df

0    1    2    3  labels  y_pred
0   5.8  4.0  1.2  0.2       0       0
1   5.1  2.5  3.0  1.1       1       1
2   6.6  3.0  4.4  1.4       1       1
3   5.4  3.9  1.3  0.4       0       0
4   7.9  3.8  6.4  2.0       2       2
5   6.3  3.3  4.7  1.6       1       1
6   6.9  3.1  5.1  2.3       2       2
7   5.1  3.8  1.9  0.4       0       0
8   4.7  3.2  1.6  0.2       0       0
9   6.9  3.2  5.7  2.3       2       2
10  5.6  2.7  4.2  1.3       1       1
11  5.4  3.9  1.7  0.4       0       0
12  7.1  3.0  5.9  2.1       2       2
13  6.4  3.2  4.5  1.5       1       1
14  6.0  2.9  4.5  1.5       1       1
15  4.4  3.2  1.3  0.2       0       0
16  5.8  2.6  4.0  1.2       1       1
17  5.6  3.0  4.5  1.5       1       1
18  5.4  3.4  1.5  0.4       0       0
19  5.0  3.2  1.2  0.2       0       0
20  5.5  2.6  4.4  1.2       1       1
21  5.4  3.0  4.5  1.5       1       1
22  6.7  3.0  5.0  1.7       1       1
23  5.0  3.5  1.3  0.3       0       0
24  7.2  3.2  6.0  1.8       2       2
25  5.7  2.8  4.1  1.3       1       1
26  5.5  4.2  1.4  0.2       0       0
27  5.1  3.8  1.5  0.3       0       0
28  6.1  2.8  4.7  1.2       1       1
29  6.3  2.5  5.0  1.9       2       2
30  6.1  3.0  4.6  1.4       1       1
31  7.7  3.0  6.1  2.3       2       2
32  5.6  2.5  3.9  1.1       1       1
33  6.4  2.8  5.6  2.1       2       2
34  5.8  2.8  5.1  2.4       2       2
35  5.3  3.7  1.5  0.2       0       0
36  5.5  2.3  4.0  1.3       1       1
37  5.2  3.4  1.4  0.2       0       0
38  6.5  2.8  4.6  1.5       1       1
39  6.7  2.5  5.8  1.8       2       2
40  6.8  3.0  5.5  2.1       2       2
41  5.1  3.5  1.4  0.3       0       0
42  6.0  2.2  5.0  1.5       2       1
43  6.3  2.9  5.6  1.8       2       2
44  6.6  2.9  4.6  1.3       1       1
45  7.7  2.6  6.9  2.3       2       2
46  5.7  3.8  1.7  0.3       0       0
47  5.0  3.6  1.4  0.2       0       0
48  4.8  3.0  1.4  0.3       0       0
49  5.2  2.7  3.9  1.4       1       1
50  5.1  3.4  1.5  0.2       0       0
51  5.5  3.5  1.3  0.2       0       0
52  7.7  3.8  6.7  2.2       2       2
53  6.9  3.1  5.4  2.1       2       2
54  7.3  2.9  6.3  1.8       2       2
55  6.4  2.8  5.6  2.2       2       2
56  6.2  2.8  4.8  1.8       2       2
57  6.0  3.4  4.5  1.6       1       1
58  7.7  2.8  6.7  2.0       2       2
59  5.7  3.0  4.2  1.2       1       1

In [82]:
# comparing actual response values (y_test) with predicted response values (y_pred) 
from sklearn import metrics 
print("kNN model accuracy:", (metrics.accuracy_score(y_test, y_pred)*100))

kNN model accuracy: 98.33333333333333


In [80]:
# making prediction for out of sample data 
sample = [[6.7,3.0,5.2,2.3], [4.3,3.0,1.1,0.1]] 
preds = knn.predict(sample) 
preds
pred_species = [iris.target_names[p] for p in preds] 
print("Predictions:", pred_species) 

Predictions: ['virginica', 'setosa']


In [83]:
# saving the model 
from sklearn.externals import joblib 
joblib.dump(knn, 'iris_knn.pkl')

['iris_knn.pkl']