<a href="https://colab.research.google.com/github/omdeshmukh/K-N-N-Classifier/blob/master/TFUpdates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==2.0.0-alpha0

     |████████████████████████████████| 79.9MB 44kB/s 
     |████████████████████████████████| 419kB 36.3MB/s 
     |████████████████████████████████| 3.0MB 27.5MB/s 
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


**1. Eager execution by default**
In TensorFlow 2.0, you no longer need to create a session and run the computational graph within that. Eager execution is enabled by default in the 2.0 release so that you can build your models and run them instantly. You can choose to disable the eager execution like so:

tf.compat.v1.disable_eager_execution() (provided tensorflow is imported with tf alias.)

Here's a little code-based comparison that shows this difference -

![alt text](https://cdn1.imggmi.com/uploads/2019/11/30/e704a3cd0c2e4b26b957136cf8a00b2f-full.png)

In [0]:
# importing tensorflow 
import tensorflow as tf 
  
# creating nodes in computation graph 
node1 = tf.constant(3, dtype=tf.int32) 
node2 = tf.constant(5, dtype=tf.int32) 
node3 = tf.add(node1, node2) 
  
# create tensorflow session object 
sess = tf.Session() 
  
# evaluating node3 and printing the result 
print("Sum of node1 and node2 is:",sess.run(node3)) 
  
# closing the session 
sess.close() 


##2. tf.function and AutoGraph 

While eager execution enables you with imperative programming, when it comes to distributed training, full-scale optimization, production environments TensorFlow 1.x style graph execution has its advantages over eager execution. In TensorFlow 2.0, you retain graph based executions but in a more flexible way. It is achieved with [tf.function](https://www.tensorflow.org/alpha/tutorials/eager/tf_function) and [AutoGraph](https://www.tensorflow.org/alpha/guide/autograph).


tf.function allows you to define TensorFlow graphs with Python-style syntax via its AutoGraph feature. AutoGraph supports a good range of Python compatibility including if-statement, for-loop, while-loop, Iterators, etc. However, there are limitations. Here you can find the complete list of supports that are currently available. Below is an example that shows you how easy it is to define a TensorFlow graph with just a decorator

In [0]:
import tensorflow as tf

# Define the forward pass
@tf.function
def single_layer(x, y):
    return tf.nn.relu(tf.matmul(x, y))

# Generate random data drawn from a uniform distribution
x = tf.random.uniform((2, 3))
y = tf.random.uniform((3, 5))

single_layer(x, y)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

<tf.Tensor: id=25, shape=(2, 5), dtype=float32, numpy=
array([[1.8779991 , 1.6349884 , 1.6660774 , 0.81102556, 1.5543084 ],
       [0.5507065 , 0.327556  , 0.40226293, 0.3816734 , 0.23649904]],
      dtype=float32)>

**3. tf.variable_scope no longer needed**

In TensorFlow 1.x, to be able to use tf.layers as variables and to reuse them, you had to use the tf.variable block. But this is no longer needed in TensorFlow 2.0. Because of the presence of keras as the center high-level API in TensorFlow 2.0, all the layers created using tf.layers can easily be put into a tf.keras.Sequential definition. This makes the code much easier to read, and you get to keep track of the variables and losses as well.

Here's an example:

In [0]:
import tensorflow as tf 
  
# creating nodes in computation graph 
node = tf.Variable(tf.zeros([2,2])) 
  
# running computation graph 
with tf.Session() as sess: 
  
    # initialize all global variables  
    sess.run(tf.global_variables_initializer()) 
  
    # evaluating node 
    print("Tensor value before addition:\n",sess.run(node)) 
  
    # elementwise addition to tensor 
    node = node.assign(node + tf.ones([2,2])) 
  
    # evaluate node again 
    print("Tensor value after addition:\n", sess.run(node)) 


In [0]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(X_train, y_train),(X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, x_test / 255.0

# Define the model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])
# Get the output probabilities
out_probs = model(X_train.astype(np.float32), training=True)
print(out_probs)

tf.Tensor(
[[0.02391199 0.07779638 0.23267893 ... 0.12131068 0.04016845 0.08540832]
 [0.04233986 0.08094802 0.07623617 ... 0.16874245 0.08631705 0.1727698 ]
 [0.04618107 0.08405012 0.07311886 ... 0.10072763 0.0787909  0.20339897]
 ...
 [0.0335169  0.10829289 0.11154137 ... 0.15243632 0.07921388 0.06846298]
 [0.08170812 0.05667927 0.10128909 ... 0.08080354 0.09516545 0.18862212]
 [0.08649439 0.09137674 0.15487011 ... 0.10834958 0.04255345 0.13164042]], shape=(60000, 10), dtype=float32)


In the above example, you passed the training data through the model just to get the raw output probabilities. Notice that it is just a forward pass. You can, of course, go ahead and train your model -

In [0]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5)
model.evaluate(X_test, y_test)

Epoch 1/5
60000/60000 [==============================] - 5s 88us/sample - loss: 0.2936 - accuracy: 0.9146
Epoch 2/5
60000/60000 [==============================] - 5s 86us/sample - loss: 0.1432 - accuracy: 0.9570
Epoch 3/5
60000/60000 [==============================] - 5s 84us/sample - loss: 0.1063 - accuracy: 0.9676
Epoch 4/5
60000/60000 [==============================] - 5s 84us/sample - loss: 0.0873 - accuracy: 0.9728
Epoch 5/5
10000/10000 [==============================] - 0s 44us/sample - loss: 2.4188 - accuracy: 0.0892


[2.4187905712127686, 0.0892]

**4. Custom layers made very easy**

In machine learning research or even in industrial applications, there is often a need for writing custom layers to cater to specific use cases. TensorFlow 2.0 makes it super easy to write a custom layer and use it along with the existing layers. You can also customize the forward pass of your model in any way you want.

In order to create a custom layer, the easiest option is to extend the Layer class from tf.keras.layers and then define it accordingly. You will create a custom layer, and then define its forward computations. The following is the output of executing help(tf.keras.layers.Layer). It tells you what things you need to specify in order to get this done:

Taking advice from the above snippet, you will -

Define the constructor with the number of the outputs  
In the build() method you will add the weights for your layer  
Finally in the call() method you will define the forward pass by chaining matrix multiplication and relu() together

In [0]:
class MyDenseLayer(tf.keras.layers.Layer):
    # Define the constructor
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    # Define the build function to add the weights
    def build(self, input_shape):
        self.kernel = self.add_variable("kernel",
                                    shape=[input_shape[-1],
                                           self.num_outputs])
    # Define the forward pass
    def call(self, input):
        matmul = tf.matmul(input, self.kernel)
        return tf.nn.relu(matmul)

# Initialize the layer with 10 output units
layer = MyDenseLayer(10)
# Supply the input shape
layer(tf.random.uniform((10,3)))
# Display the trainable parameters of the layer
print(layer.trainable_variables)

[<tf.Variable 'my_dense_layer/kernel:0' shape=(3, 10) dtype=float32, numpy=
array([[-0.05118656, -0.42643565, -0.19877958,  0.62027943,  0.1399877 ,
        -0.44563115, -0.12105483, -0.6775005 , -0.16311705, -0.3422844 ],
       [ 0.13067198,  0.08642423,  0.37010002, -0.14384723, -0.22414318,
        -0.6297847 , -0.37664208,  0.06956828,  0.14116639, -0.0602535 ],
       [-0.22287962, -0.4287195 ,  0.5242195 , -0.13652539, -0.27083334,
        -0.66345704,  0.39776742, -0.03789777, -0.4244084 ,  0.06998891]],
      dtype=float32)>]


You can compose multiple layers by extending Model class from tf.keras. 

**5. Flexibility in model training**

TensorFlow can use automatic differentiation to compute the gradients of the loss function with respect to model parameters. tf.GradientTape creates a tape within a context which is used by TensorFlow to keep track of the gradients recorded from each computation in that tape. To understand this, let's define a model in a more low-level way by extending the tf.keras.Model class.

In [0]:
from tensorflow.keras import Model

class CustomModel(Model):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.do1 = tf.keras.layers.Dropout(rate=0.2, input_shape=(14,))
        self.fc1 = tf.keras.layers.Dense(units=64, activation='relu')
        self.do2 = tf.keras.layers.Dropout(rate=0.2)
        self.fc2 = tf.keras.layers.Dense(units=64, activation='relu')
        self.do3 = tf.keras.layers.Dropout(rate=0.2)
        self.out = tf.keras.layers.Dense(units=1, activation='sigmoid')

    def call(self, x):
        x = self.do1(x)
        x = self.fc1(x)
        x = self.do2(x)
        x = self.fc2(x)
        x = self.do3(x)
        return self.out(x)

model = CustomModel()

Notice that the topology of this model is exactly the same as the one you defined earlier. To be able to train this model using automatic differentiation, you need to define the loss function and the optimizer differently -

In [0]:
loss_func = tf.keras.losses.BinaryCrossentropy()
optimizer = tf.keras.optimizers.Adam()

You will now define the metrics which will be used to measure the performance of the network during its training. By performance, model's loss and accuracy are meant here.

In [0]:
# Average the loss across the batch size within an epoch
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_acc = tf.keras.metrics.BinaryAccuracy(name='train_acc')

valid_loss = tf.keras.metrics.Mean(name='test_loss')
valid_acc = tf.keras.metrics.BinaryAccuracy(name='valid_acc')

tf.data provides utility methods to define input data pipelines. This is particularly very useful when you are dealing with a large volume of data.

You will now define the data generator, which will generate batches of data during the model's training.

In [0]:
X_train, X_test = X_train.astype(np.float32), X_test.astype(np.float32)
y_train, y_test = y_train.astype(np.int64), y_test.astype(np.int64)
y_train, y_test = y_train.reshape(-1, 1), y_test.reshape(-1, 1)

# Batches of 64
train_ds = tf.data.Dataset.from_tensor_slices((X_train, y_train)).batch(64)
test_ds = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(64)

You are now ready to train the model using tf.GradientTape. Firstly, you will define a method which will train the model with the data you just defined using tf.data.DataSet. You will also wrap the model training steps with the tf.function decorator to take advantage of the speedup it offers in the computation.

In [0]:
# Train the model
@tf.function
def model_train(features, labels):
    # Define the GradientTape context
    with tf.GradientTape() as tape:
        # Get the probabilities
        predictions = model(features)
        # Calculate the loss
        loss = loss_func(labels, predictions)
    # Get the gradients
    gradients = tape.gradient(loss, model.trainable_variables)
    # Update the weights
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    train_loss(loss)
    train_acc(labels, predictions)
# Validating the model
@tf.function
def model_validate(features, labels):
    predictions = model(features)
    t_loss = loss_func(labels, predictions)

    valid_loss(t_loss)
    valid_acc(labels, predictions)

In [0]:
for epoch in range(5):
    for features, labels in train_ds:
        model_train(features, labels)

    for test_features, test_labels in test_ds:
        model_validate(test_features, test_labels)

    template = 'Epoch {}, train_loss: {}, train_acc: {}, train_loss: {}, test_acc: {}'
    print (template.format(epoch+1,
                         train_loss.result(),
                         train_acc.result()*100,
                         valid_loss.result(),
                         valid_acc.result()*100))

**6. TensorFlow datasets**

A separate module named DataSets is used to operate with the network model in an elegant way. You already saw this in the earlier example. In this section, you will see how you can load in the MNIST dataset just in the way you want.

You can install the tensorflow_datasets library with pip. Once it is installed, you are ready to go. It provides several utility functions to help you flexibly prepare your dataset construction pipeline. You can learn more about these functions here and here. You will now see how you can build a data input pipeline to load in the MNIST dataset.

In [0]:
!pip install tensorflow_datasets

In [0]:
import tensorflow_datasets as tfds

# You can fetch the DatasetBuilder class by string
mnist_builder = tfds.builder("mnist")

# Download the dataset
mnist_builder.download_and_prepare()

# Construct a tf.data.Dataset: train and test
ds_train, ds_test = mnist_builder.as_dataset(split=[tfds.Split.TRAIN, tfds.Split.TEST])

In [0]:
# Prepare batches of 128 from the training set
ds_train = ds_train.batch(128)

# Load in the dataset in the simplest way possible
for features in ds_train:
    image, label = features["image"], features["label"]

You can now display the first image from the collection of images you loaded in. Note that tensorflow_datasets works in eager mode and in a graph based setting as well.

In [0]:
import matplotlib.pyplot as plt
%matplotlib inline

# You can convert a TensorFlow tensor just by using
# .numpy()
plt.imshow(image[0].numpy().reshape(28, 28), cmap=plt.cm.binary)
plt.show()

**7. Automatic mixed precision policy**

The mixed precision policy was proposed by NVIDIA last year. You can find the original paper here.
https://arxiv.org/abs/1710.03740  

 The brief idea behind the mixed precision policy is to use a mixture of half (FP16) and full precision (FP32) and take advantages of both the worlds. It has shown amazing results in the training of very deep neural networks (both in terms of time and score).

If you are on a CUDA enabled GPU environment (Volta Generation, Tesla T4 for example) and you installed the GPU variant of TensorFlow 2.0, you can instruct TensorFlow to train in mixed precision like so -

**os.environ['TF_ENABLE_AUTO_MIXED_PRECISION'] = '1'**

This will automatically cast the operations of a TensorFlow graph accordingly. You will be able to see a good amount of boost in your model's performance. You can also optimize TensorFlow core operations with mixed precision policy. Check this article   
https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html
  to know more about this.

**8. Distributed training**

TensorFlow 2.0 makes it super easy to distribute the training process across multiple GPUs. This is particularly useful for production purpose when you have to meet super heavy loads. This is as easy as putting your model training block inside a with block.

First, you specify a distribution strategy like so:

**mirrored_strategy = tf.distribute.MirroredStrategy()** 

A mirrored strategy creates one replica per GPU and the model variables are equally mirrored across GPUs. You can now use the defined strategy like the following:

In [0]:
with mirrored_strategy.scope():
    model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
    model.compile(loss='mse', optimizer='sgd')
    model.fit(X_train, y_train,
             validation_data=(X_test, y_test),
             batch_size=128,
             epochs=10)

Note that the above piece of code will only be useful if you have multiple GPUs configured on a single system. There are a number of distribution strategies you can configure. You can find more about it 

https://www.tensorflow.org/guide/distributed_training.

**9. TensorBoard within Jupyter Notebook**

You can visualize the model training directly within your Jupyter Notebook via TensorBoard. The new TensorBoard is loaded with a lot of exciting features like memory profiling, viewing image data including confusion matrix, conceptual model graph and so on. You can find more about this here
 https://www.tensorflow.org/tensorboard/get_started

In this section, you will configure your environment such that the TensorBoard is displayed within Jupyter Notebook. You will first have to load the tensorboard.notebook notebook extension -

%load_ext tensorboard.notebook

You will now define the TensorBoard callback using the **tf.keras.callbacks** module.

In [0]:
from datetime import datetime
import os

# Make a directory to keep the training logs
os.mkdir("logs")

# Set the callback
logdir = "logs"
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)
#Rebuild the model using the Sequential API of tf.keras -

# Define the model
model = tf.keras.Sequential([
    tf.keras.layers.Dropout(rate=0.2, input_shape=X_train.shape[1:]),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


The train and test sets were modified for different uses. So, it will be a good idea to split them once again -



In [0]:
# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
You are all ready to train the model -

# The TensorBoard extension
%tensorboard --logdir logs/
# Pass the TensorBoard callback you defined
model.fit(X_train, y_train,
         validation_data=(X_test, y_test),
         batch_size=64,
         epochs=10,
         callbacks=[tensorboard_callback],
         verbose=False)
  


The TensorBoard dashboard should be loaded in your Jupyter Notebook, and you should be able to trace the training and validation metrics.



**10. TensorFlow for Swift**

Despite all the incredible success, one thing very saddening about Python is that it is slow. To help researchers, practitioners, and even beginners, the TensorFlow team has developed a version for Swift. Although it is not as production ready as the Python variant it certainly has the potential. Swift allows for more low-level interactions and advanced compilation modules.

https://github.com/tensorflow/swift

This is where you will be able to find everything related to TensorFlow's Swift variant.

Source :  https://morioh.com/p/e4113febe7ed

https://www.datacamp.com/community/tutorials/ten-important-updates-tensorflow